// config.bin - 01:18:24 02/07/18, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled
#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

class CfgPatches {
	class simc_uaf_67_core {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"simc_uaf_67_assets"};
	};
};

class CfgUnitInsignia {
	
	class simc_1cav {
		author = "simclairdick";
		displayName = "1e Kavalerie Divisie";
		texture = "\simc_uaf_67\patches\1cav_ca.paa";
	};
	
	class simc_1cav_sub {
		author = "089";
		displayName = "1e Kavalerie Divisie (sub)";
		texture = "\simc_uaf_67\patches\1cav_sub_ca.paa";
	};
	
	class simc_1ID {
		author = "9315";
		displayName = "1e Infanterie Divisie";
		texture = "\simc_uaf_67\patches\1id_ca.paa";
	};
	
	class simc_4id {
		author = "9315";
		displayName = "4e Infanterie Divisie";
		texture = "simc_uaf_67\patches\4id_ca.paa";
	};
	
	class simc_4id_sub {
		author = "SmithKrautdo";
		displayName = "4e Infanterie Divisie (sub)";
		texture = "simc_uaf_67\patches\4id_sub_ca.paa";
	};
	
	class simc_9id {
		author = "9315";
		displayName = "9e Infanterie Divisie";
		texture = "simc_uaf_67\patches\9id_ca.paa";
	};
	
	class simc_9id_sub {
		author = "SmithKrautdo";
		displayName = "9e Infanterie Divisie (sub)";
		texture = "simc_uaf_67\patches\9id_sub_ca.paa";
	};
	
	class simc_10mtn {
		author = "BrainFag";
		displayName = "10e Gebirgsdivise";
		texture = "simc_uaf_67\patches\10mtn_ca.paa";
	};
	
	class simc_101ab {
		author = "Lackrica";
		displayName = "101e Luchtlandings Divisie";
		texture = "simc_uaf_67\patches\101ab_ca.paa";
	};
	
	class simc_101ab_sub {
		author = "Simcardigs";
		displayName = "101e Luchtlandings Divisie (sub)";
		texture = "simc_uaf_67\patches\101ab_sub_ca.paa";
	};
	
	class simc_25id {
		author = "me_irl";
		displayName = "25e Infanterie Divisie";
		texture = "simc_uaf_67\patches\25id_ca.paa";
	};
	
	class simc_25id_sub {
		author = "vagina inschiner";
		displayName = "25e Infanterie Divisie (sub)";
		texture = "simc_uaf_67\patches\25id_sub_ca.paa";
	};
	
	class simc_23id_sub {
		author = "vagina inschiner";
		displayName = "23e Infanterie Divisie (sub)";
		texture = "simc_uaf_67\patches\23id_sub_ca.paa";
	};
	
	class simc_173ab {
		author = "zingwaff";
		displayName = "173e Luchtlanding Bde.";
		texture = "simc_uaf_67\patches\173ab_ca.paa";
	};
	
	class simc_173ab_sub {
		author = "Simcardick";
		displayName = "173e Luchtlanding Bde. (sub)";
		texture = "simc_uaf_67\patches\173ab_sub_ca.paa";
	};
	
	class simc_82d {
		author = "brimcardeu";
		displayName = "82e Luchtlandings Divisie";
		texture = "simc_uaf_67\patches\82d_ca.paa";
	};
	
	class simc_82d_sub {
		author = "Simcardick";
		displayName = "82e Luchtlandings Divisie (sub)";
		texture = "simc_uaf_67\patches\82d_sub_ca.paa";
	};
};

class CfgFactionClasses {
	
	class Simc_UA_65 
	{
		displayName = "US Army (65)";
        author = "Simcardo";
        icon = "\simc_uaf_67_preview\icons\factoid_ua_nac_ca.paa"; 
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 3;
        side = 1; // Blufor        
	};
	
	class Simc_UA_68 
	{
		displayName = "US Army (68)";
        author = "Simcardo";
        icon = "\simc_uaf_67_preview\icons\factoid_ua_ca.paa"; 
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 3;
        side = 1; // Blufor        
	};
	
	class Simc_UA_67 
	{
		displayName = "US Army (67)";
        author = "Simcardo";
        icon = "\simc_uaf_67_preview\icons\factoid_ua_ca.paa"; 
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 3;
        side = 1; // Blufor        
	};
	
	class Simc_UA_69 
	{
		displayName = "US Army (69)";
        author = "Simcardo";
        icon = "\simc_uaf_67_preview\icons\factoid_ua_ca.paa"; 
        flag = "\A3\ui_f\data\map\markers\flags\USA_ca.paa";
        priority = 3;
        side = 1; // Blufor        
	};
};

class CfgEditorSubcategories {
	class SIMC_men_tcu
	{
		displayName="Men (TCU/Late)";
	};
	
	class SIMC_men_tcu_erla
	{
		displayName="Men (TCU)";
	};
	
	class SIMC_men_og107_mk1
	{
		displayName="Men (OG107)";
	};	
	
	class SIMC_men_og107_mk3
	{
		displayName="Men (OG107/Late)";
	};
	
	class SIMC_men_erdl
	{
		displayName="Men (ERDL)";
	};
};

class CfgGlasses {
	class None;	// External class reference
		
	class G_simc_US_Bandoleer_556 : None {
		author = "Brainfag";
		scope = public;
		displayName = "Bandoleer (duplet)";
		model = "\simc_uaf_67\bandolier_3.p3d";
		picture = "\simc_uaf_67_preview\icons\bandoiler_ca.paa"; 
		hiddenSelections[] = {"blow"};
		hiddenSelectionsTextures[] = {""};
		identityTypes[] = {"Simc_UA67", 0.5};
	};
		
	class G_simc_US_Bandoleer_556_left : G_simc_US_Bandoleer_556 {
		author = "Casper";
		displayName = "Bandoleer";
		model = "\simc_uaf_67\bandolier_2.p3d";
		hiddenSelections[] = {"blow"};
		hiddenSelectionsTextures[] = {""};
		identityTypes[] = {"Simc_UA67", 0.5};
	};
	
	class G_simc_US_Bandoleer_556_right : G_simc_US_Bandoleer_556_left {
		author = "Nil-acht-neun";
		model = "\simc_uaf_67\bandolier_3.p3d";
		hiddenSelections[] = {"bleft"};
		hiddenSelectionsTextures[] = {""};
		identityTypes[] = {"Simc_UA67", 0.5};
	};	
	
	class G_simc_US_Bandoleer_556_fore : G_simc_US_Bandoleer_556_left {
		author = "Nil-acht-neun";
		model = "\simc_uaf_67\bandolier_fore.p3d";
		hiddenSelections[] = {"lows"};
		hiddenSelectionsTextures[] = {""};
		identityTypes[] = {"Simc_UA67", 0.5};
	};	
	
	#define lens_clr 		"\simc_uaf_67\jewgel\glass_ca.paa" 
	#define lens_jellwick	"\simc_uaf_67\jewgel\glass_jellwick_ca.paa" 
	#define lens_green		"\simc_uaf_67\jewgel\glass_green_ca.paa" 
	#define lens_red		"\simc_uaf_67\jewgel\glass_red_ca.paa" 
	
	
	class G_SWDG : None {
		scope = 2;
		author = "Olmo Potums";
		displayname = "(US) M-1944 SWDG";
		model = "simc_uaf_67\swdg.p3d";
		picture = "\simc_uaf_67_preview\icons\swdg_ca.paa";
		hiddenSelections[] = {"glass", "jewgel_low"};
		hiddenSelectionsTextures[] = {lens_red, ""};
		identityTypes[] = {};		
	};
	
	class G_SWDG_low : G_SWDG {
		scope = 2;
		author = "Olmo Potums";
		hiddenSelections[] = {"glass", "jewgel"};
		hiddenSelectionsTextures[] = {lens_green, ""};
	};
};


class EventHandlers;
class CfgVehicles {
	
	//humans
	
	class Man;	// External class reference
	
	class CAManBase : Man {
		class HitPoints {
			class HitFace;	// External class reference
			class HitNeck;	// External class reference
			class HitHead;	// External class reference
			class HitPelvis;	// External class reference
			class HitAbdomen;	// External class reference
			class HitDiaphragm;	// External class reference
			class HitChest;	// External class reference
			class HitBody;	// External class reference
			class HitArms;	// External class reference
			class HitHands;	// External class reference
			class HitLegs;	// External class reference
		};
	};
	
	class SoldierWB : CAManBase {};
	
	class B_Soldier_base_F : SoldierWB {};
	
	#define A3_Verwundet "a3\characters_f\heads\data\hl_white_bald_muscular.rvmat", "a3\characters_f\heads\data\hl_white_bald_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_white_bald_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_black_bald_muscular.rvmat", "a3\characters_f\heads\data\hl_black_bald_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_black_bald_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_white_hairy_muscular.rvmat", "a3\characters_f\heads\data\hl_white_hairy_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_white_hairy_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_white_old.rvmat", "a3\characters_f\heads\data\hl_white_old_injury.rvmat", "a3\characters_f\heads\data\hl_white_old_injury.rvmat", "a3\characters_f\heads\data\hl_asian_bald_muscular.rvmat", "a3\characters_f\heads\data\hl_asian_bald_muscular_injury.rvmat", "a3\characters_f\heads\data\hl_asian_bald_muscular_injury.rvmat" 
	
	class simc_ua_67_base : B_Soldier_base_F {
		scope = protected;
		author = "smicdaro";
		side = TWest;
		identityTypes[] = {"LanguageENG_F", "Head_NATO", "Simc_UA67"};
		faction = Simc_UA_67;
		selectionClan = "";
		genericNames = "EnglishMen";
		model = "\simc_uaf_67\tcu_mk3.p3d";
		hiddenSelections[] = {"camo", "camo2", "rank", "insignia"};
		hiddenSelectionsTextures[] = {"\simc_uaf_67\data\tcu_mk3_co.paa", "\simc_uaf_67\data\tcu_mk3_co.paa", "", ""};
		portrait = "\simc_uaf_67_preview\potret\sns_wip_co.paa";
		editorPreview = "\simc_uaf_67_preview\preview\sns_wip.jpg";
		displayName = "Human";
		weapons[] = {"Throw", "Put"};
		respawnWeapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnMagazines[] = {};
		uniformClass = "U_Simc_TCU_mk3";
		headgearProbability = 100;
		headgearList[] = {"H_Simc_M1_bitch_ns", 1, "H_Simc_M1_bitch_up",1, "H_Simc_M1_bitch_op", 0.3, "H_Simc_M1_bitch_op_2", 1, "H_Simc_M1_bitch_low", 1, "H_Simc_M1_bitch_low_rot", 1, "H_Simc_M1_bitch_flip_ns", 0.1, "H_Simc_M1_bitch_flip_op_2", 0.1, "H_Simc_M1_bitch_flip_op", 0.1};
		linkedItems[] = {"H_Simc_M1_bitch_ns", "V_Simc_56", "ItemMap", "ItemCompass", "ItemWatch"};
		respawnLinkedItems[] = {"H_Simc_M1_bitch_ns", "V_Simc_56", "ItemMap", "ItemCompass", "ItemWatch"};
		backpack = "";
		cost = 100000;
		accuracy = 1.5;	// accuracy needed to recognize type of this target
		camouflage = 1.8;	// how dificult to spot - bigger - better spotable
		armor = 2;
		armorStructural = 0.4;
		explosionShielding = 0.04;
		
		class EventHandlers: EventHandlers
		{
			init = "if (local (_this select 0)) then {[(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
		};
		
		class Wounds {
			tex[] = {};
			mat[] = {"simc_uaf_67\data\tcu_mk3.rvmat", "simc_uaf_67\data\tcu_mk3_verwundet.rvmat", "simc_uaf_67\data\tcu_mk3_verwundet.rvmat", "simc_uaf_67\data\tcu_mk3.rvmat", "simc_uaf_67\data\tcu_mk3_verwundet.rvmat", "simc_uaf_67\data\tcu_mk3_verwundet.rvmat", A3_Verwundet};
		};
		
		class PlateInfos
		{
		    // name of section where plate number should generated
		     name = "nom";
		     // color used for plate number in (r,g,b,a) format
		     color[] = {0,0,0,0.9};
		     plateFont        = "PuristaSemiBold";
		     // "#" represent number & "$" represents letter
		//   plateFormat        = profileName;
		     plateFormat        = "GAY####";
		     // Required even if you don't use any letters in plateFormat
		     plateLetters    = "ABCDEFHIKLMOPRSTVXYZ";
		};
	};
	
	#include "humans.hpp"

	//rearpacks!
	
	class B_AssaultPack_rgr; //external class reference 
	class B_simc_pack_56 : B_AssaultPack_rgr {
		displayName = "[US] Pack";
		author = "Smicradeu";
		scope = protected;
		descriptionShort = "sack";	
		model = "\simc_uaf_67\pack_LW_1.p3d";
		hiddenSelections[] = {""};
		hiddenSelectionsTextures[] = {""};
		picture = "\simc_uaf_67_preview\icons\pack_frem_ca.paa";
	};	
	
	#include "pakets.hpp"
	
	#include "grounds.hpp"
};	

class CfgWeapons {
	class Uniform_Base;	// External class reference
	
	class ItemCore;	// External class reference
	
	class U_BasicBody : Uniform_Base {
		class ItemInfo;	// External class reference
	};
	
	class U_Simc_67_BasicBody : U_BasicBody {
		author = "Simcardigs";
		scope = private;
		model = "\simc_uaf_67\suitpack_og107.p3d";
		hiddenSelections[] = {""};
		hiddenSelectionsTextures[] = {""};
		picture = "\simc_uaf_67_preview\icons\sns_wip_ca.paa";
		
		class ItemInfo : ItemInfo {
			containerClass = "Supply30";
			mass = 20;
		};
	};
	
	class U_Simc_OG107_mk1 : U_Simc_67_BasicBody {
		author = "sim-kar98-dough";
		scope = public;
		displayName = "[US] OG-107 1952";
		model = "\simc_uaf_67\suitpack_og107.p3d";
		picture = "\simc_uaf_67_preview\icons\og107_ca.paa";
		descriptionShort = "Uniform, Fatigues, OG-107";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_og107_mk1";
		};
	};	
	
	class U_Simc_OG107_mk1_trop : U_Simc_OG107_mk1 {
		author = "Brijnvag";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_og107_mk1_trop";
		};
	};
	
	class U_Simc_OG107_mk3 : U_Simc_OG107_mk1 {
		author = "Brijnvag";
		scope = public;
		displayName = "[US] OG-107 1964";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_og107_mk3";
		};
	};
	
	class U_Simc_TCU_mk3 : U_Simc_67_BasicBody {
		author = "Casper_TFG";
		scope = public;
		displayName = "[US] Tropical Combat Fatigues 1967";
		model = "\simc_uaf_67\suitpack_tcu.p3d";	
		picture = "\simc_uaf_67_preview\icons\tcu_ca.paa";	
		descriptionShort = "Uniform, Combat, Tropical, OG-107";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk3";
		};
	};
	
	class U_Simc_TCU_mk3_trop: U_Simc_TCU_mk3 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk3_trop";
		};
	};
	
	class U_Simc_TCU_mk3_poplijn : U_Simc_TCU_mk3 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk3_poplijn";
		};
	};
	
	class U_Simc_TCU_mk3_poplijn_trop: U_Simc_TCU_mk3 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk3_poplijn_trop";
		};
	};
	
	class U_Simc_TCU_mk1 : U_Simc_TCU_mk3 {
		author = "Casper_TFG";
		scope = public;
		displayName = "[US] Tropical Combat Fatigues 1963";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk1";
		};
	};
	
	class U_Simc_TCU_mk1_trop: U_Simc_TCU_mk1 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk1_trop";
		};
	};
	
	class U_Simc_TCU_mk1_roll: U_Simc_TCU_mk1 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk1_roll";
		};
	};
	
	class U_Simc_TCU_mk2 : U_Simc_TCU_mk3 {
		author = "Casper_TFG";
		scope = public;
		displayName = "[US] Tropical Combat Fatigues 1966";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk2";
		};
	};
	
	class U_Simc_TCU_mk2_trop: U_Simc_TCU_mk2 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk2_trop";
		};
	};
	
	class U_Simc_TCU_mk2_roll: U_Simc_TCU_mk2 {
		author = "Casper_TFG";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_mk2_roll";
		};
	};
	
	class U_Simc_TCU_mk3_erdl : U_Simc_TCU_mk3 {
		author = "Dopest Ghast in stad";
		scope = public;
		displayName = "Tropical Combat Fatigues ERDL";
		model = "\simc_uaf_67\suitpack_tcu.p3d";	
		picture = "\simc_uaf_67_preview\icons\tcu_ca.paa";	
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\simc_uaf_67\data\tcu_mk3_erdl_co.paa"};
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_erdl_l";
		};
	};
	
	class U_Simc_TCU_mk3_erdl_top : U_Simc_TCU_mk3_erdl {
		author = "nil-acht-neun";
		scope = public;	
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_erdl_top";
		};
	};
	
	class U_Simc_TCU_mk3_erdl_low : U_Simc_TCU_mk3_erdl {
		author = "vagina engineer";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_erdl_low";
		};
	};
	
	class U_Simc_TCU_tee : U_Simc_TCU_mk3 {
		author = "Faggot";
		scope = public;
		displayName = "Tropical Combat Fatigues (tee)";
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee";
		};
	};
	
	class U_Simc_TCU_tee_weiss : U_Simc_TCU_tee {
		author = "Brainless Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_weiss";
		};
	};
	
	class U_Simc_TCU_tee_long : U_Simc_TCU_tee {
		author = "Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_long";
		};
	};
	
	class U_Simc_TCU_tee_long_weiss : U_Simc_TCU_tee_long {
		author = "Brainless Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_long_weiss";
		};
	};
	
	class U_Simc_TCU_tee_top : U_Simc_TCU_tee {
		author = "Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_top";
		};
	};
	
	class U_Simc_TCU_tee_top_weiss : U_Simc_TCU_tee_top {
		author = "Brainless Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_top_weiss";
		};
	};
	
	class U_Simc_TCU_tee_erdl : U_Simc_TCU_tee {
		author = "Brainless Faggot";
		displayName = "Tropical Combat Fatigues ERDL (tee)";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_erdl";
		};
	};
	
	class U_Simc_TCU_tee_erdl_weiss : U_Simc_TCU_tee_erdl {
		author = "Brainless Faggot";
		scope = public;
		
		class ItemInfo : ItemInfo {
			uniformClass = "simc_tcu_tee_erdl_weiss";
		};
	};
			
	//hmelets
	
	
	class H_HelmetB : ItemCore {
		class ItemInfo;	// External class reference
	};
	
	class H_Simc_M1_67_base : H_HelmetB {
		author = "Motta + Ethridge + 089";
		scope = protected;
		displayName = "[US] M1 Helmet";
		picture = "\simc_uaf_67_preview\icons\pot_btich_ca.paa";
		model = "\simc_uaf_67\helmet_m1_F.p3d";
		hiddenSelections[] = {"starpe"};
		hiddenSelectionsTextures[] = {""};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_op.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"starpe"};
			hiddenSelectionsTextures[] = {""};
			
			class HitpointsProtectionInfo {
				class Head {
					hitpointName = "HitHead";
					armor = 5;
					passThrough = 0.8;
				};
			};
		};
	};
	
	//covers_define
		
	#define shell	 	"\simc_uaf_67\data\pot_co.paa"
	#define shell_2	 	"\simc_uaf_67\data\pot_2_co.paa"
	#define kentang 	"\simc_uaf_67\data\cover_kentang_co.paa"
	#define green	 	"\simc_uaf_67\data\cover_green_dirt_co.paa"
	#define tan	 		"\simc_uaf_67\data\cover_tan_dirt_co.paa"
	#define bitch	 	"\simc_uaf_67\data\cover_bitch_co.paa"
	#define bitch_dirt	"\simc_uaf_67\data\cover_bitch_dirt_co.paa"
	#define bitch_red	"\simc_uaf_67\data\cover_bitch_rot_co.paa"
	#define bitch_flip	"\simc_uaf_67\data\cover_bitch_flip_co.paa"
	#define bitch_flip_dirt	"\simc_uaf_67\data\cover_bitch_flip_dirt_co.paa"
	#define erdl	 	"\simc_uaf_67\data\cover_erdl_co.paa"
	
	
	class H_Simc_M1_bitch_op : H_Simc_M1_67_base {
		author = "Mo + Eth + 089 + Justin + Cat + Lak";
		scope = public;
		displayName = "[US] M1 Helmet (Mitchell)";
		picture = "\simc_uaf_67_preview\icons\pot_bitch_ca.paa";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_Op.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_up : H_Simc_M1_bitch_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		model = "\simc_uaf_67\helmet_m1_up.p3d";
		hiddenSelectionsTextures[] = {bitch_red};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_up.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_ns : H_Simc_M1_bitch_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_dirt};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_F.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_low : H_Simc_M1_bitch_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		model = "\simc_uaf_67\helmet_m1_low.p3d";
		hiddenSelectionsTextures[] = {bitch_dirt};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_low.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_low_rot : H_Simc_M1_bitch_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover", "shell", "ben"};
		hiddenSelectionsTextures[] = {bitch_red, shell_2, ""};
		model = "\simc_uaf_67\helmet_m1_low.p3d";
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_low.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover", "shell", "ben"};
		};
	};
		
	class H_Simc_M1_bitch_op_2 : H_Simc_M1_bitch_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		model = "\simc_uaf_67\helmet_m1_OP.p3d";
		hiddenSelections[] = {"cover", "shell", "starpe"};
		hiddenSelectionsTextures[] = {bitch_red, shell_2, ""};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_OP.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover", "shell", "starpe"};
		};
	};
	
	class H_Simc_M1_bitch_low_op : H_Simc_M1_bitch_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover", "starpe", "ben"};
		hiddenSelectionsTextures[] = {bitch, ""};
		model = "\simc_uaf_67\helmet_m1_low.p3d";
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_low.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover", "starpe", "ben"};
		};
	};
	
	class H_Simc_M1_bitch_swdg : H_Simc_M1_bitch_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		displayName = "[US] M1 Helmet (Mitchell/SWDG)";
		Model = "\simc_uaf_67\helmet_m1_swdg.p3d";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_dirt};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_swdg.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_flip_op : H_Simc_M1_67_base {
		author = "Mo + Eth + 089 + Justin + Lakarak";
		scope = public;
		displayName = "[US] M1 Helmet (Mitchell-tan)";
		picture = "\simc_uaf_67_preview\icons\pot_tan_ca.paa";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_flip};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_Op.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_flip_up : H_Simc_M1_bitch_flip_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_flip_dirt};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_up.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_flip_ns : H_Simc_M1_bitch_flip_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_flip};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_F.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_flip_low : H_Simc_M1_bitch_flip_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_flip_dirt};
		model = "\simc_uaf_67\helmet_m1_low.p3d";
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_low.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_bitch_flip_op_2 : H_Simc_M1_bitch_flip_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		model = "\simc_uaf_67\helmet_m1_OP.p3d";
		hiddenSelections[] = {"cover", "shell", "starpe"};
		hiddenSelectionsTextures[] = {bitch_flip_dirt, shell_2, ""};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_OP.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover", "shell", "starpe"};
		};
	};
	
	class H_Simc_M1_bitch_flip_swdg : H_Simc_M1_bitch_flip_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		displayName = "[US] M1 Helmet (Mitchell-tan/SWDG)";
		Model = "\simc_uaf_67\helmet_m1_swdg.p3d";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {bitch_flip};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_swdg.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	#include "bitch_ben.hpp"
	
	
	class H_Simc_M1_erdl_op : H_Simc_M1_67_base {
		author = "Mo + Eth + 089 + Justin + Lak";
		scope = public;
		displayName = "[US] M1 Helmet (ERDL)";
		picture = "\simc_uaf_67_preview\icons\pot_erdl_ca.paa";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {erdl};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_Op.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_erdl_ns : H_Simc_M1_erdl_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {erdl};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_F.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_erdl_up : H_Simc_M1_erdl_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {erdl};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_up.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class H_Simc_M1_erdl_op_2 : H_Simc_M1_erdl_op {
		author = "Mo + Eth + 089 + Justin + Lak";
		model = "\simc_uaf_67\helmet_m1_low.p3d";
		hiddenSelections[] = {"cover", "ben"};
		hiddenSelectionsTextures[] = {erdl, ""};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_low.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover", "ben"};
		};
	};
	
	class H_Simc_M1_erdl_swdg : H_Simc_M1_erdl_ns {
		author = "Mo + Eth + 089 + Justin + Lak";
		displayName = "[US] M1 Helmet (ERDL/SWDG)";
		hiddenSelections[] = {"cover"};
		hiddenSelectionsTextures[] = {erdl};
		
		class ItemInfo : ItemInfo {
			mass = 30;
			uniformModel = "\simc_uaf_67\helmet_m1_swdg.p3d";
			modelSides[] = {6};
			hiddenSelections[] = {"cover"};
		};
	};
	
	class VestItem;	// External class reference	
	
	class Vest_Camo_Base;  // External class reference
	
	#define m56_1 "\simc_uaf_67\data\gear_56_co.paa" 
	#define m56_2 "\simc_uaf_67\data\gear_56_laat_co.paa" 
	
	#include "vetts.hpp"
	
	//bandoleers_NVO
	class NVGoggles;
	class HeadgearItem;
	
	class bandolier_addon : NVGoggles {
		author = "Brainfag";
		scope = public;
		displayName = "Bandoleer";
		model = "\simc_uaf_67\bandolier_drop.p3d";
		picture = "\simc_uaf_67_preview\icons\bandoiler_ca.paa"; 
		hiddenSelections[] = {"blow"};
		hiddenSelectionsTextures[] = {""};			
		modelOptics = "\A3\Weapons_F\empty";
		visionMode[] = {"Normal", "Normal"};
		descriptionShort = "American Bandoleer (decorative)";
		
		class ItemInfo
		{
			type = 616;
			hmdType = 0;
			uniformModel = "simc_uaf_67\bandolier_3.p3d";
			modelOff = "simc_uaf_67\bandolier_3.p3d";
			hiddenSelections[] = {"blow"};
			hiddenSelectionsTextures[] = {""};		
			mass = 2;
		};
	};
	
	class bandolier_addon_left : bandolier_addon {
		author = "Casper";
		hiddenSelections[] = {"blow", "bright"};
		hiddenSelectionsTextures[] = {""};
		class ItemInfo
		{
			type = 616;
			hmdType = 0;
			uniformModel = "simc_uaf_67\bandolier_2.p3d";
			modelOff = "simc_uaf_67\bandolier_2.p3d";
			hiddenSelections[] = {"blow", "bright"};
			hiddenSelectionsTextures[] = {""};		
			mass = 2;
		};
	};
	
	class bandolier_addon_right : bandolier_addon {
		author = "Nil-acht-neun";
		hiddenSelections[] = {"blow", "bright"};
		hiddenSelectionsTextures[] = {""};
		class ItemInfo
		{
			type = 616;
			hmdType = 0;
			uniformModel = "simc_uaf_67\bandolier_3.p3d";
			modelOff = "simc_uaf_67\bandolier_3.p3d";
			hiddenSelections[] = {"blow", "bleft"};
			hiddenSelectionsTextures[] = {""};		
			mass = 2;
		};
	};
	
	class bandolier_addon_fore : bandolier_addon {
		author = "Nil-acht-neun";
		hiddenSelections[] = {"lows"};
		hiddenSelectionsTextures[] = {""};
		class ItemInfo
		{
			type = 616;
			hmdType = 0;
			uniformModel = "simc_uaf_67\bandolier_fore.p3d";
			modelOff = "simc_uaf_67\bandolier_fore.p3d";
			hiddenSelections[] = {"lows"};
			hiddenSelectionsTextures[] = {""};		
			mass = 2;
		};
	};
};	
	
	